version: "3.8"

services:
  # FIWARE Orion Context Broker
  orion:
    image: fiware/orion:latest
    container_name: orion
    ports:
      - "1026:1026"
    # Adiciona logLevel para mais detalhes e checagem de saúde
    command: [ "-dbURI", "mongodb://mongo:27017", "-logLevel", "INFO" ]
    depends_on:
      - mongo

  # MongoDB
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"

  # FIWARE Cygnus
  cygnus:
    image: fiware/cygnus-ngsi:latest
    container_name: cygnus
    ports:
      - "5055:5055"
      - "5080:5080" # <-- Expor a porta da API de administração do Cygnus
    environment:
      - CYGNUS_POSTGRESQL_HOST=postgres
      - CYGNUS_POSTGRESQL_PORT=5432
      - CYGNUS_POSTGRESQL_USER=fiware
      - CYGNUS_POSTGRESQL_PASS=fiware
      - CYGNUS_POSTGRESQL_DATABASE=fiware
      - CYGNUS_SERVICE_PORT=5055
      - CYGNUS_API_PORT=5080 # <-- Habilitar a API de admin
      # - CYGNUS_LOG_LEVEL=DEBUG # PARA DEBUGS
      - CYGNUS_LOG_LEVEL=INFO
      - CYGNUS_AGENT_NAME=cygnus-ngsi
      - CYGNUS_POSTGRESQL_ATTR_PERSISTENCE=row
      - CYGNUS_POSTGRESQL_DATA_MODEL=dm-by-entity
      # - CYGNUS_POSTGRESQL_DATA_MODEL=dm-by-table
    depends_on:
      - orion
      - postgres

  # ... (outros serviços como postgres e grafana permanecem iguais) ...
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=fiware
      - POSTGRES_PASSWORD=fiware
      - POSTGRES_DB=fiware
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres


  # Serviço Python
  python_script:
    build: ./python_app
    container_name: python_script
    environment:
      - ORION_URL=http://orion:1026/v2/entities
      - ORION_SUBSCRIPTION_URL=http://orion:1026/v2/subscriptions
      - PYTHONUNBUFFERED=1 # <-- Garante que logs do Python não fiquem em buffer
    depends_on:
      - orion
      - cygnus
    command: ["python", "load_to_orion.py"]

volumes:
  postgres_data: